// Handles admin upload panel and user management
const AcademicFile = require("../models/AcademicFile");
const User = require("../models/User");
const fs = require("fs");
const path = require("path");

// ─── Helper: upload or replace a PDF by type ─────────────────────────────────
// Used by all three upload handlers below
// Deletes the previous file from disk before saving the new one

const uploadPDFByType = async (type, req, res) => {
  try {
    // Multer has already saved the file to disk at this point
    // req.file contains the uploaded file info
    if (!req.file) {
      return res.status(400).json({ message: "No PDF file uploaded." });
    }

    // Check if there is an existing file of this type — if so, delete it
    const existing = await AcademicFile.findOne({ type }).sort({ createdAt: -1 });

    if (existing) {
      // Build path to the old file on disk and delete it
      const oldFilePath = path.join(
        __dirname,
        "../uploads/pdfs",
        type,
        existing.filePath
      );
      if (fs.existsSync(oldFilePath)) {
        fs.unlinkSync(oldFilePath);
      }

      // Remove old record from database
      await existing.deleteOne();
    }

    // Save the new file record to the database
    const newFile = await AcademicFile.create({
      type,
      originalName: req.file.originalname,  // original filename from user's machine
      filePath: req.file.filename,           // stored filename generated by multer
      uploadedBy: req.user._id,
    });

    const populated = await newFile.populate("uploadedBy", "name role");

    // Build accessible URL for the frontend
    const fileUrl = `/uploads/pdfs/${type}/${newFile.filePath}`;

    res.status(201).json({
      message: `${type.charAt(0).toUpperCase() + type.slice(1)} PDF uploaded successfully.`,
      file: {
        _id: newFile._id,
        type: newFile.type,
        originalName: newFile.originalName,
        fileUrl,
        uploadedBy: populated.uploadedBy,
        uploadedAt: newFile.createdAt,
      },
    });
  } catch (error) {
    res.status(500).json({ message: error.message || "Server error." });
  }
};

// ─── @route   POST /api/admin/upload/routine ─────────────────────────────────
// ─── @desc    Upload or replace the Routine PDF
// ─── @access  Private (admin only)

const uploadRoutine = (req, res) => uploadPDFByType("routine", req, res);

// ─── @route   POST /api/admin/upload/result ──────────────────────────────────
// ─── @desc    Upload or replace the Result PDF
// ─── @access  Private (admin only)

const uploadResult = (req, res) => uploadPDFByType("result", req, res);

// ─── @route   POST /api/admin/upload/seatplan ────────────────────────────────
// ─── @desc    Upload or replace the Seat Plan PDF
// ─── @access  Private (admin only)

const uploadSeatPlan = (req, res) => uploadPDFByType("seatplan", req, res);

// ─── @route   GET /api/admin/users ───────────────────────────────────────────
// ─── @desc    Get all registered users (students and teachers only)
// ─── @access  Private (admin only)

const getAllUsers = async (req, res) => {
  try {
    const users = await User.find({ role: { $ne: "admin" } })
      .select("-password")
      .sort({ createdAt: -1 });

    res.status(200).json({ users });
  } catch (error) {
    res.status(500).json({ message: error.message || "Server error." });
  }
};

// ─── @route   DELETE /api/admin/users/:id ────────────────────────────────────
// ─── @desc    Delete a user account
// ─── @access  Private (admin only)

const deleteUser = async (req, res) => {
  try {
    const user = await User.findById(req.params.id);

    if (!user) {
      return res.status(404).json({ message: "User not found." });
    }

    // Prevent admin from deleting their own account
    if (user.role === "admin") {
      return res.status(400).json({ message: "Admin account cannot be deleted." });
    }

    // Delete avatar from disk if it exists
    if (user.avatar) {
      const avatarPath = path.join(__dirname, "../uploads/images", user.avatar);
      if (fs.existsSync(avatarPath)) {
        fs.unlinkSync(avatarPath);
      }
    }

    await user.deleteOne();

    res.status(200).json({ message: "User deleted successfully." });
  } catch (error) {
    res.status(500).json({ message: error.message || "Server error." });
  }
};

module.exports = {
  uploadRoutine,
  uploadResult,
  uploadSeatPlan,
  getAllUsers,
  deleteUser,
};